### ISSUE TITLE
How to clear cache

### ISSUE THREAD

**Issue by shirubei** [JJRobertsSex30/ChatGPT-Q-A-Chatbot-with-custom-data#1]
I've made a python pg to give it a try. Everything seemed so good. 
But after changing all data in the traning.txt to some completly different stuff , I found that those old contents still showed up as answers.
It seemed that those old ones were cached in openai server side.
Is that true and any suggestions to delete these caches or walk round ? Thank you !

**Comment by JJRobertsSex30** [comment]
Yeah the answers are based on the index.json file.

the training.txt is only used to create the vectorised index.json file which is why, after the first time you run the program, you can comment out the line that asks the program to do the training because the .json file only needs to be generated once.

So just delete index.json and run the training again to create the new .json file based on your new training.txt

**Comment by shirubei** [comment]
> Yeah the answers are based on the index.json file.
> 
> the training.txt is only used to create the vectorised index.json file which is why, after the first time you run the program, you can comment out the line that asks the program to do the training because the .json file only needs to be generated once.
> 
> So just delete index.json and run the training again to create the new .json file

Thanks for your reply. My bad for not enough explaination.
I've delete the index.json manually and run python pg again .
But those old contents stiil alive.

**Comment by JJRobertsSex30** [comment]
quitting the program and restarting it again should be enough but check to make sure you have successfully created a new index.json file and take a look at the contents of that file at the top to see if the text is correcttly showing your new training.txt info.

**Comment by shirubei** [comment]
Thanks again. 
I did have a look into the newly created index.json and found that there old contents in it! 
I had thought that index was build based on training.txt . But it was the whole "data" folder. 
I've left the old contents in another file which was in the "data" folder too.
Just moved the old ones to other place and everything is OK.
Thank you,  You saved me!

**Comment by JJRobertsSex30** [comment]
yes when you run training it runs against all the files in that directory
so if there are 2 text files in there it will vectorise them both when
creating the index.json file
